trigger:
- main

pool:
  name: dhurander

stages:
- stage: Terraform_Init
  displayName: "Terraform Init"

  jobs:
  - job: TerraformJob
    displayName: "Terraform Job"

    steps:

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
        backendServiceArm: 'new-hero'
        backendAzureRmResourceGroupName: 'info-infra'
        backendAzureRmStorageAccountName: 'storageaccountinfra'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'my-app.tfstate'
