trigger:
- main

pool:
  name: aajkerat

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- script: |
    terraform init -reconfigure
  displayName: Terraform Init

- script: |
    terraform plan
  displayName: Terraform Plan

- script: |
    terraform apply -auto-approve
  displayName: Terraform Apply